"""Copia os dados do SQLite local para o PostgreSQL apontado por DATABASE_URL.

Uso:
    set DATABASE_URL=postgresql://usuario:senha@host:5432/plataforma
    .venv\\Scripts\\python.exe tools\\migrar_para_postgres.py            # so copia
    .venv\\Scripts\\python.exe tools\\migrar_para_postgres.py --limpar   # zera o Postgres antes

Detalhes:
  * as tabelas sao copiadas em ordem de dependencia (pai antes do filho);
  * os ids originais sao preservados (as tabelas usam GENERATED BY DEFAULT);
  * no fim as sequences sao realinhadas com setval() e os totais comparados;
  * sem --limpar o script recusa um Postgres que ja tenha dados.
"""
from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))
import config  # noqa: E402
import db  # noqa: E402

# Ordem respeitando as chaves estrangeiras: sempre quem e referenciado vem antes.
ORDEM = ["usuarios", "materias", "modulos", "perguntas", "alternativas", "flashcards",
         "simulados", "simulado_materias", "simulado_questoes", "tentativas", "respostas",
         "progresso", "anotacoes"]


def colunas_sqlite(origem: sqlite3.Connection, tabela: str) -> list[str]:
    return [r[1] for r in origem.execute(f"PRAGMA table_info({tabela})")]


def copiar(origem, destino, tabela: str, colunas: list[str]) -> tuple[int, int]:
    marcadores = ", ".join(["?"] * len(colunas))
    sql = f"INSERT INTO {tabela} ({', '.join(colunas)}) VALUES ({marcadores})"
    linhas = origem.execute(f"SELECT {', '.join(colunas)} FROM {tabela}").fetchall()
    for linha in linhas:
        db.run(destino, sql, list(linha))
    return len(linhas), db.q1(destino, f"SELECT COUNT(*) FROM {tabela}")[0]


def realinhar_sequence(destino, tabela: str, colunas: list[str]) -> None:
    if "id" not in colunas:
        return
    total = db.q1(destino, f"SELECT COALESCE(MAX(id), 0) FROM {tabela}")[0]
    if not total:
        return
    db.q1(destino, f"SELECT setval(pg_get_serial_sequence('{tabela}', 'id'), {total}, true)")


def principal() -> int:
    if not config.usar_postgres():
        print("[erro] defina DATABASE_URL antes de rodar a migracao (ela e o destino).")
        return 2
    origem = sqlite3.connect(config.DB_PATH)
    origem.row_factory = sqlite3.Row
    if not config.DB_PATH.exists():
        print(f"[erro] banco de origem nao encontrado: {config.DB_PATH}")
        return 2

    limpar = "--limpar" in sys.argv
    destino = db.conectar_postgres(config.dsn_postgres())

    existentes = {r[0] for r in db.q(
        destino, "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'")}
    if limpar:
        print("[1/3] zerando o schema public do destino")
        destino.executescript("DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
        existentes = set()
    db.criar_tabelas(destino, verbose=False)

    ja_preenchidas = [t for t in ORDEM if t in existentes and db.q1(destino, f"SELECT COUNT(*) FROM {t}")[0]]
    if ja_preenchidas:
        print(f"[erro] o destino ja tem dados em: {', '.join(ja_preenchidas)}. "
              f"Use --limpar para sobrescrever.")
        return 2

    print(f"[2/3] copiando de {config.DB_PATH} para {db.resumo()}")
    falhas = 0
    for tabela in ORDEM:
        colunas = colunas_sqlite(origem, tabela)
        se, sd = copiar(origem, destino, tabela, colunas)
        realinhar_sequence(destino, tabela, colunas)
        marca = "ok" if se == sd else "DIVERGE"
        falhas += se != sd
        print(f"  {tabela:<20}{se:>6} -> {sd:<6} {marca}")

    destino.commit()
    print("[3/3]", "totais conferem" if not falhas else f"{falhas} tabela(s) com total divergente")
    print("usuario de teste:", db.q1(
        destino, "SELECT usuario, papel FROM usuarios WHERE papel = 'admin' LIMIT 1"))
    origem.close()
    destino.close()
    return 1 if falhas else 0


if __name__ == "__main__":
    raise SystemExit(principal())
